# Testbench Makefile

BUILD_NAME = mux2

RELATIVE_PROJECT_PATH = general/mux2

TB_SOURCE = $(PROJECT_ROOT)/$(RELATIVE_PROJECT_PATH)/mux2_tb.v
TB_INCLUDE = $(PROJECT_ROOT)/$(RELATIVE_PROJECT_PATH)/mux2.v
